#!/usr/bin/env node
/**
 * install-hooks.mjs
 *
 * Installs a git pre-commit hook that automatically bumps the version
 * in package.json before every commit.
 *
 * Run automatically via: npm install  (triggered by the "prepare" script)
 * Or manually:           node scripts/install-hooks.mjs
 */

import { existsSync, mkdirSync, writeFileSync, chmodSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const hooksDir = join(root, ".git", "hooks");

if (!existsSync(join(root, ".git"))) {
  // Not a git repo (e.g. CI/CD deploy) — skip silently
  process.exit(0);
}

if (!existsSync(hooksDir)) {
  mkdirSync(hooksDir, { recursive: true });
}

const hookPath = join(hooksDir, "pre-commit");
const hookContent = `#!/bin/sh
# Auto-generated by scripts/install-hooks.mjs — do not edit manually.
node "$(git rev-parse --show-toplevel)/scripts/bump-version.mjs"
git add package.json
`;

writeFileSync(hookPath, hookContent);
chmodSync(hookPath, 0o755);
console.log("install-hooks: pre-commit hook installed at .git/hooks/pre-commit");
